#This is the makefile that can be run with our code on terminal. - Maryfrances & Carolina

PROGRAMS = auto

CFLAGS = -g -std=c99 -Wall -Werror

main:
	$(CC) $(CFLAGS) -o $(PROGRAMS) *.c

clean:
	-rm $(PROGRAMS) *.o
	-rm -rf $(PROGRAMS) auto.dSYM