#
#FILE: makefile
#MEMBER: Maryfrances Umeora
#NETID: mumeora
#

PROGRAMS = boolp

CFLAGS = -g -std=c99 -Wall -Werror

main: 
	$(CC) $(CFLAGS) -o $(PROGRAMS) *.c

clean:
	-rm $(PROGRAMS) *.o
	-rm -rf $(PROGRAMS) *.dSYM 
