#
#FILE: makefile
#MEMBERS: Maryfrances Umeora, Carolina Lion He
#NETIDs: mumeora, clionhe
#

PROGRAMS = rexp

CFLAGS = -g -std=c99 -Wall -Werror

main: 
	$(CC) $(CFLAGS) -o $(PROGRAMS) *.c

clean:
	-rm $(PROGRAMS) *.o
	-rm -rf $(PROGRAMS) *.dSYM
